### PR TITLE
Add code to retrieve COPD, HF, and PNA cohorts

### PR DESCRIPTION
**Pull request by Franck-Dernoncourt**
I have created a new folder `/code/cohorts` where MIMIC users can add the cohort definition they use for their studies.

### CODE REVIEW

**Comment by tompollard** [comment]
Thanks Franck

**Comment by tompollard** [comment]
@Franck-Dernoncourt Thanks for sharing your code here. I'm preparing to delete this repository, so please could you move it to the MIMIC Code Repo (https://github.com/MIT-LCP/mimic-code)? Or I can move it there if you prefer...

**Comment by Franck-Dernoncourt** [comment]
Sounds good I'll take care of it this week. I've got a deadline on Tuesday, then I'll go through all issues + code posted here and move whatever is useful for MIMIC-III to other other repo+SE. Thanks!

**Comment by tompollard** [comment]
That would be great, thanks Franck. Good luck with the deadline!

**Comment by Franck-Dernoncourt** [comment]
Just to make sure: do you plan to move the issues labeled with "migrate_to_build_repo" to https://github.com/MIT-LCP/mimic-iii-building ?

**Pull request merged**
